Update cbsodata3.py
J535D165/cbsodata pull request #11
Opened 2019-09-04 17:03 UTC by ncvanegmond

added positional arguments for functions get_table_list and _download_metadata to allow for use of proxies

2019-09-04 21:12 UTC, J535D165 requested changes
Thanks for this PR! Interesting feature. 

A couple of remarks before merging. 

1. Can you add this option for the other functions (like get_data, get_info, ... ) as well? 
2. Add proxies to Options class. Add `self.proxies = None` here https://github.com/J535D165/cbsodata/blob/a29827add5c44dbacd24c3b2c0d153aa69237f8f/cbsodata/cbsodata3.py#L52-L54 Use the option manager within the functions to get the global option. See example below. 

```python
def get_info(table_id, catalog_url=None, proxies=None):
    """Get information about a table.
    Parameters
    ----------
    table_id : str
        The identifier of the table.
    catalog_url : str
        The url of the catalog. Default "opendata.cbs.nl".
    Returns
    -------
    dict
        Table information
    """

    _proxies = options.proxies if proxies is None else proxies

    info_list = _download_metadata(
        table_id,
        "TableInfos",
        catalog_url=_get_catalog_url(catalog_url),
        proxies = proxies
    )

    if len(info_list) > 0:
        return info_list[0]
    else:
        return None

```

Usage:

```python
import cbsodata

cbsodata.options.proxies = "MY PROXIES"

cbsodata.get_info("82070ENG")
```

which is the same as 
```python
import cbsodata

cbsodata.get_info("82070ENG", proxies = "MY PROXIES")
```

2019-09-04 21:12 UTC, J535D165 commented on cbsodata/cbsodata3.py
> +def get_table_list(select=None, filters=None, catalog_url=None, proxies=None):
Please add docstring.

2019-09-05 13:20 UTC, J535D165 commented
Great implementation. 

The tests fail due to style errors https://travis-ci.org/J535D165/cbsodata/jobs/581151465. Thereafter, I can merge. 

Would you like to have a new release on the short term? 

(FYI @jolienoomens)

2019-09-05 13:45 UTC, ncvanegmond commented
Thanks for considering the PR, and all your feedback and patience. First time making a pull requests, so figuring it out as I go :) Think I got all errors this time around.

If you would be able to do a new release on the short-term, that would be much appreciated! Very helpful library, even more so now we can use it behind a proxy ;)

2019-09-05 19:53 UTC, J535D165 approved these changes

2019-09-05 19:56 UTC, merged

2019-09-05 20:04 UTC, J535D165 commented
Thanks, merged and a new release on PyPI. Good work for your first PR!

Note. Add support for proxies in odata4 #8.